site_name: Jonathan (Jon) Harper
site_description: Projects, articles, and thoughts by Jon Harper
site_author: Jon Harper
site_url: https://jon-harper.github.io
edit_uri: ""
copyright: Copyright &copy; 2022 Jonathan Harper

theme:
  name: material
  custom_dir: overrides
  logo: img/doug.png
  palette:
    primary: blue
    accent: orange
  font:
    text: Noto Sans
  features:
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - neoteroi.cards

plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jonspaceharper
      name: LinkedIn Profile
    - icon: fontawesome/brands/github
      link: https://github.com/jon-harper
      name: "GitHub: jon-harper"
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/4732082/jonspaceharper
      name: "Stack Overflow: jonspaceharper"
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/user/jonspaceharper
      name: "Reddit: u/jonspaceharper"
    - icon: fontawesome/regular/newspaper
      link: https://post.news/jonspaceharper
      name: "Post.news: jonspaceharper"
    - icon: simple/kofi
      link: https://ko-fi.com/jonspaceharper
      name: Support me on Ko-Fi!

extra_css:
  - assets/stylesheets/neoteroi.css
  - assets/stylesheets/extra.css

nav:
  - index.md
  - about.md
  - resume.md
  - Projects:
    - projects/omnibox.md
    - E34M1: "https://jon-harper.github.io/E34M1/"
    - projects/clockmaker.md
    - projects/clock3.md

