site_name: Jonathan (Jon) Harper
site_description: Projects, articles, and thoughts by Jon Harper
site_author: Jon Harper
site_url: https://jon-harper.github.io
edit_uri: ""
copyright: Copyright &copy; 2022 Jonathan Harper

theme:
  name: material
  custom_dir: overrides
  logo: img/doug.png
  palette:
    # scheme: slate
    primary: blue
    accent: orange
  font:
    text: Noto Sans
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - neoteroi.cards

plugins:
  # - search
  - glightbox:
      skip_classes:
        - skip-lightbox

extra:
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/jonspaceharper
      name: Support me on Ko-Fi!
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jonspaceharper
      name: LinkedIn Profile
    - icon: fontawesome/brands/github
      link: https://github.com/jon-harper
      name: "GitHub: jon-harper"
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/4732082/jonspaceharper
      name: "Stack Overflow: jonspaceharper"
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/jonspaceharper
      name: "Twitter: jonspaceharper"
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/user/jonspaceharper
      name: "Reddit: u/jonspaceharper"
    - icon: simple/mastodon
      link: https://mastodon.online/@jonspaceharper
      name: "Mastodon: jonspaceharper@mastodon.online"

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/neoteroi.css

nav:
  - index.md
  - about.md
  - contact.md
  - Projects:
    - OmniBox:
      - projects/omnibox.md
      # - projects/omnibox_gallery.md
      - Documentation Link: "https://jon-harper.github.io/OmniBox"
    - Clock3:
      - projects/clock3.md
      # - projects/clock3_gallery.md
      - Documentation Link: "https://jon-harper.github.io/clock-3"
    - projects/clockmaker.md

  - External Links:
    - Thingiverse Designs: "https://www.thingiverse.com/jonspaceharper/designs"
    - GitHub Repositories: "https://github.com/jon-harper?tab=repositories"

