site_name: jonspaceharper
site_description: Articles and thoughts by Jon Harper
site_author: Jon Harper
site_url: https://jon-harper.github.io

theme:
  name: material

markdown_extensions:
  - admonition

nav:
  - index.md
  - General:
    - about.md
    - contact.md
  - Projects:
    - projects/omnibox.md
    - projects/clock3.md
    - projects/clockmaker.md
    # - projects/eva_contrib_extras.md
    - Thingiverse Designs:
      - ReFiller Filament Roller: "https://www.thingiverse.com/thing:4605360"
      - Tactical, Belt-Mounted Sriracha Dispenser: "https://www.thingiverse.com/thing:5418923"
      - All Designs: "https://www.thingiverse.com/jonspaceharper/designs"
    - GitHub Repositories: "https://github.com/jon-harper?tab=repositories"
  # - articles.md

